export const DISPLAY_LOADING = 'DISPLAY_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const DISPLAY_LOADING_CHECKOUT = 'DISPLAY_LOADING_CHECKOUT'
export const HIDE_LOADING_CHECKOUT = 'HIDE_LOADING_CHECKOUT'